#!/bin/bash

SEC ()
{
  echo "\subsection{$1}"
}


INS ()   # mnemonic, short title
{
  echo "\subsubsection*{$1\index{$1} -- $2}"
  #echo "\hspace{0.5cm}"
  echo "\begin{minipage}[t][1\totalheight]{1\columnwidth}"
  echo "\begin{labeling}{Flags~affected:}"
}


COD ()   # Code (fields separated by spaces)
{
  echo "\item [{Code:}] %"
  echo "\begin{minipage}[b][1\totalheight]{1\columnwidth}%"
  echo "\begin{tabular}{|c|c|c|c|c|c|c|c|}"
  echo "\hline"
  echo "{\scriptsize 31\hfill26} & {\scriptsize 25\hfill21} & {\scriptsize 20\hfill16} & {\scriptsize 15\hfill11} & {\scriptsize 10} & {\scriptsize 9\hfill8} & {\scriptsize 7\hfill4} & {\scriptsize 3\hfill0}\tabularnewline"
  echo "\hline \hline"
#  echo "\texttt{\verb#$1#} & \texttt{\verb#$2#} & \texttt{\verb#$3#} & \texttt{\verb#$4#} & \texttt{\verb#$5#} & \texttt{\verb#$6#} & \texttt{\verb#$7#} & \texttt{\verb#$8#}\tabularnewline"
  echo "\verb.$1. & \verb.$2. & \verb.$3. & \verb.$4. & \verb.$5. & \verb.$6. & \verb.$7. & \verb.$8. \tabularnewline"
  echo "\hline"
  echo "\end{tabular}%"
  echo "\end{minipage}"
}


FMT ()   # Format (mnemonic)
{
  echo "\item [{Format:}] \texttt{$@}"
}


DES ()   # Description
{
  echo "\item [{Description:}] $@"
}


DE_ ()   # Description cont'd
{
  echo "\par $@"
}


OPE ()   # Operation
{
  echo "\item [{Operation:}] \texttt{$@}"
}


OP_ ()   # Operation cont'd
{
  echo "\\\\ \texttt{$@}"
}


FLA ()   # Flags affected
{
  echo "\item [{Flags~affected:}] \texttt{$@}"
}


EXC ()
{
  echo "\item [{Exceptions:}] $@"
}


END ()
{
  echo "\end{labeling}"
  echo "\medskip{}"
  echo "\end{minipage}"
  echo
}


if [[ "$1" == "" ]]; then
  echo "Usage: $0 <instructions file> <output file>"
else
  . $1 > $2
fi



